# Generated by Django 2.2.4 on 2020-01-20 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.SmallIntegerField(default=None)),
                ('ema_order', models.SmallIntegerField(default=None)),
                ('interest', models.SmallIntegerField(default=-1)),
                ('mood', models.SmallIntegerField(default=-1)),
                ('sleep', models.SmallIntegerField(default=-1)),
                ('fatigue', models.SmallIntegerField(default=-1)),
                ('weight', models.SmallIntegerField(default=-1)),
                ('worthlessness', models.SmallIntegerField(default=-1)),
                ('concentrate', models.SmallIntegerField(default=-1)),
                ('restlessness', models.SmallIntegerField(default=-1)),
                ('suicide', models.SmallIntegerField(default=-1)),
                ('time_expected', models.BigIntegerField(default=0)),
                ('time_responded', models.BigIntegerField(default=0)),
                ('lof_value', models.FloatField(default=-1)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
