# Generated by Django 2.2.4 on 2020-01-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='stress',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
