# Generated by Django 2.2.4 on 2020-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0002_response_stress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='concentrate',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='fatigue',
            new_name='answer2',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='interest',
            new_name='answer3',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='mood',
            new_name='answer4',
        ),
        migrations.RemoveField(
            model_name='response',
            name='restlessness',
        ),
        migrations.RemoveField(
            model_name='response',
            name='sleep',
        ),
        migrations.RemoveField(
            model_name='response',
            name='stress',
        ),
        migrations.RemoveField(
            model_name='response',
            name='suicide',
        ),
        migrations.RemoveField(
            model_name='response',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='response',
            name='worthlessness',
        ),
    ]
