# Generated by Django 2.2.4 on 2020-01-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200120_1339'),
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_sp',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='acc_sw',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='app_usage_stats',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='audio_loudness',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='geofencing',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='gps_locations',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='hrm',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='light_intensity',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='max_dist_from_home',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='max_dist_two_locations',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='num_of_dif_places',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='phone_calls',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='radius_of_gyration',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='significant_motion',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='stationary_dur',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='stddev_of_displacement',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='step_detector',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='total_dist_covered',
            name='lof_value',
        ),
        migrations.RemoveField(
            model_name='unlocked_dur',
            name='lof_value',
        ),
        migrations.AddField(
            model_name='activities',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app_usage_stats',
            name='day_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app_usage_stats',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audio_loudness',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gps_locations',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='light_intensity',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone_calls',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='significant_motion',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationary_dur',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step_detector',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unlocked_dur',
            name='ema_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='activity_duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.BigIntegerField(default=0)),
                ('timestamp_end', models.BigIntegerField(default=0)),
                ('activity_type', models.TextField(blank=True, default='')),
                ('duration', models.IntegerField(default=0)),
                ('ema_order', models.SmallIntegerField(default=0)),
                ('day_num', models.SmallIntegerField(default=0)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
