# Generated by Django 2.2.4 on 2020-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_auto_20200120_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrm',
            name='username',
        ),
        migrations.DeleteModel(
            name='acc_sw',
        ),
        migrations.DeleteModel(
            name='hrm',
        ),
    ]
