# Generated by Django 2.2.4 on 2020-01-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200126_1804'),
        ('sensor_data', '0003_auto_20200123_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='screen_on_dur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.BigIntegerField(default=0)),
                ('timestamp_end', models.BigIntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('ema_order', models.SmallIntegerField(default=0)),
                ('day_num', models.SmallIntegerField(default=0)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
