# Generated by Django 2.2.4 on 2020-01-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200120_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='daily_data_size_smartwatch',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='heartbeat_smartwatch',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_ds_smartwatch',
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartbeat_smartphone',
            field=models.BigIntegerField(default=1579761275.299183),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_ds_smartphone',
            field=models.BigIntegerField(default=1579761275.299183),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_login_datetime',
            field=models.BigIntegerField(default=1579761275.299183),
        ),
        migrations.AlterField(
            model_name='participant',
            name='register_datetime',
            field=models.BigIntegerField(default=1579761275.299183),
        ),
    ]
