# Generated by Django 2.2.4 on 2020-01-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200128_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppackagetocategorymap',
            name='category',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartbeat_smartphone',
            field=models.BigIntegerField(default=1580176715.670473),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_ds_smartphone',
            field=models.BigIntegerField(default=1580176715.670473),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_login_datetime',
            field=models.BigIntegerField(default=1580176715.670473),
        ),
        migrations.AlterField(
            model_name='participant',
            name='register_datetime',
            field=models.BigIntegerField(default=1580176715.670473),
        ),
    ]
