# Generated by Django 2.2.4 on 2020-01-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200128_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='total_data_submitted',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='heartbeat_smartphone',
            field=models.BigIntegerField(default=1580448355.296853),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_ds_smartphone',
            field=models.BigIntegerField(default=1580448355.296853),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_login_datetime',
            field=models.BigIntegerField(default=1580448355.295826),
        ),
        migrations.AlterField(
            model_name='participant',
            name='register_datetime',
            field=models.BigIntegerField(default=1580448355.295826),
        ),
    ]
